name: run-tests-with-coverage

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/run-tests-with-coverage.yml'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: xdebug

      - name: Install dependencies
        run: |
          composer require "laravel/framework:12.*" "orchestra/testbench:10.*" --no-interaction --no-update
          composer update --prefer-dist --no-interaction

      - name: Execute tests with coverage
        run: vendor/bin/pest --coverage --min=100

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/clover.xml
          fail_ci_if_error: true